# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f36be95423b61e85e8f8401fa2302811c7f5a9513a697a77888d3fccae9a3e885cfa4dfbf3235cec66e7404581bfafd14cd977c641f4efabfa900005f4829ba

test:
  secret_key_base: 4e99691dd2c927cb57d39d541fdd811165a54de08ba64b5c10d8b2911d9b52795d2b73e345b4c6d5f62ba19537516ce655d423bb274154e5af698f31329d4cc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
